const jugadores = [
  {
    nombre: "Bruno Garay",
    posicion: "LW, MI",
    equipo: "Equipazo FC",
    edad: "21",
    nacionalidad: "Uruguayo",
    dorsal: 7,
    imagen: "./Bruno.jpg",
    goles: 46,
    asistencias: 44,
    valoracion: 6.7,
  },
  {
    nombre: "Pablinho Méndez",
    posicion: "DC, MCO",
    equipo: "Equipazo FC",
    edad: "20",
    nacionalidad: "Uruguayo",
    dorsal: 10,
    imagen: "./Pablo.jpg",
    goles: 518,
    asistencias: 211,
    valoracion: 8.0,
  },
  {
    nombre: "German Centurión",
    posicion: "MC, MP",
    equipo: "Equipazo FC",
    edad: "20",
    nacionalidad: "Uruguayo",
    dorsal: 22,
    imagen: "./Faku.jpg",
    goles: 64,
    asistencias: 53,
    valoracion: 7.4,
  },
  {
    nombre: "Maciel Galeano",
    posicion: "DC, SDD",
    equipo: "Equipazo FC",
    edad: "22",
    nacionalidad: "Uruguayo",
    dorsal: 10,
    imagen: "./Maxi.jpg",
    goles: 18,
    asistencias: 7,
    valoracion: 6.4,
  },
  {
    nombre: "Ignacio Lima",
    posicion: "MC, MCD",
    equipo: "Equipazo FC",
    edad: "21",
    nacionalidad: "Uruguayo",
    dorsal: 5,
    imagen: "./Nacho.png",
    goles: 4,
    asistencias: 1,
    valoracion: 6.8,
  },
  {
    nombre: "Franco Méndez",
    posicion: "RW, MC, MCD",
    equipo: "Equipazo FC",
    edad: "22",
    nacionalidad: "Uruguayo",
    dorsal: 5,
    imagen: "./Franco.jpg",
    goles: 141,
    asistencias: 252,
    valoracion: 7.9,
  },
  {
    nombre: "Manuel Perera",
    posicion: "MCD, MCO, DC",
    equipo: "Equipazo FC",
    edad: "21",
    nacionalidad: "Uruguayo",
    dorsal: 20,
    imagen: "./Manu.png",
    goles: 126,
    asistencias: 164,
    valoracion: 7.1,
  },
];

export default jugadores;
