const jugadores = [
  {
    nombre: "Bruno Garay",
    posicion: "LW, MI",
    equipo: "Equipazo FC",
    edad: "21",
    nacionalidad: "Uruguayo",
    dorsal: 7,
    imagen: "./Bruno.jpg",
    goles: 0.14,
    asistencias: 0.13,
    valoracion: 6.7,
  },
  {
    nombre: "Pablinho Méndez",
    posicion: "DC, MCO",
    equipo: "Equipazo FC",
    edad: "20",
    nacionalidad: "Uruguayo",
    dorsal: 10,
    imagen: "./Pablo.jpg",
    goles: 0.78,
    asistencias: 0.32,
    valoracion: 8.0,
  },
  {
    nombre: "German Centurión",
    posicion: "MC, MP",
    equipo: "Equipazo FC",
    edad: "20",
    nacionalidad: "Uruguayo",
    dorsal: 22,
    imagen: "./Faku.jpg",
    goles: 0.27,
    asistencias: 0.22,
    valoracion: 7.4,
  },
  {
    nombre: "Maciel Galeano",
    posicion: "DC, SDD",
    equipo: "Equipazo FC",
    edad: "22",
    nacionalidad: "Uruguayo",
    dorsal: 10,
    imagen: "./Maxi.jpg",
    goles: 0.17,
    asistencias: 0.06,
    valoracion: 6.4,
  },
  {
    nombre: "Ignacio Lima",
    posicion: "MC, MCD",
    equipo: "Equipazo FC",
    edad: "21",
    nacionalidad: "Uruguayo",
    dorsal: 5,
    imagen: "./Nacho.png",
    goles: 0.08,
    asistencias: 0.02,
    valoracion: 6.8,
  },
  {
    nombre: "Franco Méndez",
    posicion: "RW, MC, MCD",
    equipo: "Equipazo FC",
    edad: "22",
    nacionalidad: "Uruguayo",
    dorsal: 5,
    imagen: "./Franco.jpg",
    goles: 0.32,
    asistencias: 0.58,
    valoracion: 7.9,
  },
  {
    nombre: "Manuel Perera",
    posicion: "MCD, MCO, DC",
    equipo: "Equipazo FC",
    edad: "21",
    nacionalidad: "Uruguayo",
    dorsal: 20,
    imagen: "./Manu.png",
    goles: 0.22,
    asistencias: 0.29,
    valoracion: 7.1,
  },
];

export default jugadores;
